### ISSUE TITLE
Editor creates a new line when I apply and unapply bold/italic to a full line.

### ISSUE THREAD

**Issue by halilb** [chrisdavies/minidoc#19]
https://user-images.githubusercontent.com/2227041/110168847-d3039e80-7e08-11eb-94d9-fc9536543fdb.mov

**Comment by chrisdavies** [comment]
Interesting. I'm not able to reproduce. What browser are you using?

**Comment by halilb** [comment]
I'm using Google Chrome 89.0.4389.82 on MacOS.

Managed to narrow down the issue to triple clicking on a word - which selects the whole line. I believe the triple clicking behaviour is somehow behaving different on my browser.

Created a test case for this issue that produces the same output with my browser:

```
it('selects a whole line with triple clicks and toggles h1', async () => {
  const toolbarDoc = `<p>Hello friend</p><p>How are you?</p>`;
  await loadDoc(toolbarDoc);
  await page.click('text=Hello', {
    clickCount: 3,
  });
  await page.click('[aria-label="Heading 1"]');
  expect(await serializeDoc()).toEqual(`<h1>Hello friend</h1><p>How are you?</p>`);
});
```

It fails on both chromium and webkit with this error: `Error: Expected '<h1>Hello friend</h1><h1>How are you?</h1>' to equal '<h1>Hello friend</h1><p>How are you?</p>'.`

Debugged it for a while but couldn't see any problems in the minidoc realm. The event returned from `selectionchange` is probably different.

**Comment by chrisdavies** [comment]
Swank. Thanks, Halil! I'll see if I can reproduce it.

**Comment by chrisdavies** [comment]
Still couldn't get the bold / italic to reproduce, but the triple click h1 toggle did reproduce. I added your test and fixed the bug. I decided to override triple click rather than fix it in the range logic, because the range logic is correct for most cases, and fixing it there broke other scenarios.

I wonder if this fix also fixes your italic / bold bug?

**Comment by halilb** [comment]
> Still couldn't get the bold / italic to reproduce, but the triple click h1 toggle did reproduce. I added your test and fixed the bug. I decided to override triple click rather than fix it in the range logic, because the range logic is correct for most cases, and fixing it there broke other scenarios.
> 
> I wonder if this fix also fixes your italic / bold bug?

Finally managed to reproduce that italic/bold bug. It's not happening on a regular line, and only happening when the paragraph has `<br>` at the end. And I noticed we're leaving a `br`tag inside the paragraph when you add and delete a new line.

Here is a video about it:


https://user-images.githubusercontent.com/2227041/110341061-00d02980-803b-11eb-851c-f443f60f13b5.mov
